name: Kotlin Multiplatform CI

on:
  push:
    branches:
      - "main"
      - "story/sr*"
      - "bug/sr*"
      - "release/"
  pull_request:
    branches:
      - "story/sr*"
      - "bug/sr*"
      - "release/"

permissions:
  contents: read

jobs:
  build:
    name: Build and Test KMP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: android
          - os: macos-latest
            target: ios

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK for Android and common builds
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Add permissions for gradlew
      - name: Make Gradlew Executable
        run: chmod +x gradlew

      # Set up Android SDK (if building Android)
      - name: Set up Android SDK
        if: matrix.target == 'android'
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0

      # Install Kotlin Multiplatform dependencies
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # Run build and test for all targets
      - name: Build and Test
        run: |
          ./gradlew clean build
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

#  ios:
#    name: Build iOS
#    runs-on: macos-latest
#    steps:
#      # Checkout the repository
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      # Set up JDK for Kotlin
#      - uses: actions/checkout@v3
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'temurin'

      # Install dependencies
#      - name: Install dependencies
#        run: |
#          brew install cocoapods
#          pod install
#        shell: bash

      # Build iOS Framework
#      - name: Build iOS
#        run: |
#          ./gradlew :shared:packForXcode
